"""Harvest candidate questions from real vLLM GitHub issues.

The golden set is sourced from issues people actually filed, not generated by a
model. That is a deliberate and defensible choice: a synthetic set is written in
the vocabulary of the documentation it was generated from, so it flatters
retrieval and measures the wrong thing. Real issues carry the vocabulary gap
between how a user asks and how the docs are written, which is precisely the
failure this system has to survive.

Harvesting only produces *candidates*. Most are environment-specific debugging
reports that no documentation could answer. Curation into the golden set is a
separate, human-reviewed step, because "is this answerable from the corpus" is a
judgement and getting it wrong silently corrupts every number downstream.

Fetching shells out to the GitHub CLI rather than embedding a token: `gh` is
already authenticated on a development machine, and this is a one-off dev task
that never runs in CI.
"""

from __future__ import annotations

import json
import re
import subprocess
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

# vLLM's issue templates prefix the title with the kind of report.
_TITLE_PREFIX = re.compile(
    r"^\s*\[(usage|doc|docs|question|feature|bug|installation)\]\s*:?\s*", re.I
)

# The section of the [Usage] template holding the actual question. Everything
# above it is an environment dump and everything below is checkbox boilerplate.
_QUESTION_HEADING = re.compile(r"^###\s+How would you like to use vllm\s*$", re.I | re.MULTILINE)
_ENV_HEADING = re.compile(r"^###\s+Your current environment\s*$", re.I | re.MULTILINE)
_BOILERPLATE_HEADING = re.compile(r"^###\s+Before submitting a new issue", re.I | re.MULTILINE)


@dataclass(frozen=True)
class Candidate:
    """One harvested issue, before any curation judgement."""

    number: int
    url: str
    title: str
    raw_title: str
    question: str
    labels: tuple[str, ...]
    created_at: str
    state: str


def strip_title_prefix(title: str) -> str:
    """Remove the template tag from an issue title.

    "[Usage]: How do I set max_num_seqs" becomes "How do I set max_num_seqs".
    The tag says which template was used, not anything about the question.
    """
    return _TITLE_PREFIX.sub("", title).strip()


def extract_question(body: str) -> str:
    """The question text from a vLLM issue body.

    Prefers the template's question section. Falls back to the whole body when
    the template was not followed, which is common: a plain body is still a real
    question, and dropping it would bias the set toward template-followers.

    The environment dump is always removed. It is many hundreds of tokens of
    package versions that would dominate any embedding of the question.
    """
    if not body:
        return ""

    text = body.replace("\r\n", "\n")

    match = _QUESTION_HEADING.search(text)
    if match:
        text = text[match.end() :]
    else:
        # No question heading. Drop an environment section if one is present,
        # keeping whatever follows it.
        env = _ENV_HEADING.search(text)
        if env:
            after = text[env.end() :]
            next_heading = re.search(r"^###\s+", after, re.MULTILINE)
            text = after[next_heading.start() :] if next_heading else after

    boilerplate = _BOILERPLATE_HEADING.search(text)
    if boilerplate:
        text = text[: boilerplate.start()]

    return text.strip()


def parse_issue(payload: dict[str, Any]) -> Candidate:
    """Turn one GitHub search result into a Candidate.

    Typed as Any because this is a decoded JSON payload from an external API:
    asserting a stricter shape here would be a claim about GitHub's response
    that nothing verifies.
    """
    raw_title = str(payload.get("title", ""))
    labels_raw = payload.get("labels") or []
    labels = tuple(
        str(label["name"]) for label in labels_raw if isinstance(label, dict) and "name" in label
    )
    return Candidate(
        number=int(payload["number"]),
        url=str(payload.get("html_url", "")),
        title=strip_title_prefix(raw_title),
        raw_title=raw_title,
        question=extract_question(str(payload.get("body") or "")),
        labels=labels,
        created_at=str(payload.get("created_at", "")),
        state=str(payload.get("state", "")),
    )


def fetch_candidates(
    label: str = "usage",
    pages: int = 3,
    per_page: int = 100,
    repo: str = "vllm-project/vllm",
) -> list[Candidate]:
    """Fetch issues through the GitHub CLI.

    Sorted by reactions rather than recency: a question several people hit is
    more representative of the real query distribution than whatever was filed
    most recently, and reaction count is the only popularity signal the search
    API exposes for issues.
    """
    candidates: list[Candidate] = []
    for page in range(1, pages + 1):
        query = (
            f"search/issues?q=repo:{repo}+is:issue+label:{label}"
            f"&sort=reactions&order=desc&per_page={per_page}&page={page}"
        )
        try:
            result = subprocess.run(
                ["gh", "api", query],
                capture_output=True,
                text=True,
                check=True,
                encoding="utf-8",
            )
        except FileNotFoundError as exc:
            raise RuntimeError(
                "the GitHub CLI is required to harvest; install gh and run `gh auth login`"
            ) from exc
        except subprocess.CalledProcessError as exc:
            raise RuntimeError(f"gh api failed: {exc.stderr.strip()}") from exc

        items = json.loads(result.stdout).get("items", [])
        if not items:
            break
        candidates.extend(parse_issue(item) for item in items)
    return candidates


def write_candidates(path: Path, candidates: list[Candidate]) -> int:
    """Write candidates as JSONL. Returns how many were written."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        for candidate in candidates:
            handle.write(json.dumps(asdict(candidate), ensure_ascii=False) + "\n")
    return len(candidates)


def read_candidates(path: Path) -> list[Candidate]:
    if not path.is_file():
        return []
    out: list[Candidate] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.strip():
            data = json.loads(line)
            data["labels"] = tuple(data.get("labels", ()))
            out.append(Candidate(**data))
    return out
